// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GaugeUpdater is an autogenerated mock type for the GaugeUpdater type
type GaugeUpdater struct {
	mock.Mock
}

// GaugeUpdate provides a mock function with given fields: key, value
func (_m *GaugeUpdater) GaugeUpdate(key string, value float64) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGaugeUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewGaugeUpdater creates a new instance of GaugeUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGaugeUpdater(t mockConstructorTestingTNewGaugeUpdater) *GaugeUpdater {
	mock := &GaugeUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
