// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Updater is an autogenerated mock type for the Updater type
type Updater struct {
	mock.Mock
}

// UpdateBatch provides a mock function with given fields: ctx, gauges, counters
func (_m *Updater) UpdateBatch(ctx context.Context, gauges [][]string, counters [][]string) error {
	ret := _m.Called(ctx, gauges, counters)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, [][]string, [][]string) error); ok {
		r0 = rf(ctx, gauges, counters)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdater creates a new instance of Updater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdater(t mockConstructorTestingTNewUpdater) *Updater {
	mock := &Updater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
