// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CounterUpdater is an autogenerated mock type for the CounterUpdater type
type CounterUpdater struct {
	mock.Mock
}

// CounterUpdate provides a mock function with given fields: key, value
func (_m *CounterUpdater) CounterUpdate(key string, value int64) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCounterUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewCounterUpdater creates a new instance of CounterUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCounterUpdater(t mockConstructorTestingTNewCounterUpdater) *CounterUpdater {
	mock := &CounterUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
