// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Pinger is an autogenerated mock type for the Pinger type
type Pinger struct {
	mock.Mock
}

// Ping provides a mock function with given fields: ctx
func (_m *Pinger) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPinger interface {
	mock.TestingT
	Cleanup(func())
}

// NewPinger creates a new instance of Pinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPinger(t mockConstructorTestingTNewPinger) *Pinger {
	mock := &Pinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
