// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MetricGeter is an autogenerated mock type for the MetricGeter type
type MetricGeter struct {
	mock.Mock
}

// GetMetric provides a mock function with given fields: ctx, typ, key
func (_m *MetricGeter) GetMetric(ctx context.Context, typ string, key string) (string, error) {
	ret := _m.Called(ctx, typ, key)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, typ, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, typ, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, typ, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMetricGeter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMetricGeter creates a new instance of MetricGeter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMetricGeter(t mockConstructorTestingTNewMetricGeter) *MetricGeter {
	mock := &MetricGeter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
